Check if a Windows image is sysprepped
In InstallUnattend task, check if the image is sysprepped. If this is
not the case, then fail.

diff --git a/snf-image-helper/common.sh.in b/snf-image-helper/common.sh.in
--- a/snf-image-helper/common.sh.in
+++ b/snf-image-helper/common.sh.in
@@ -1,4 +1,4 @@
-# Copyright (C) 2011-2015 GRNET S.A. and individual contributors
+# Copyright (C) 2011-2016 GRNET S.A. and individual contributors
 # Copyright (C) 2007, 2008, 2009 Google Inc.
 #
 # This program is free software; you can redistribute it and/or modify
@@ -845,6 +845,57 @@ get_windows_nt_version() {
         echo ${BASH_REMATCH[1]} ${BASH_REMATCH[2]}
     else
         log_error "Can't decode CurrentVersion registry key: $current_version"
+    fi
+}
+
+check_windows_if_sysprepped() {
+    local target state
+    target="$1"
+
+    # https://technet.microsoft.com/en-us/library/hh824815.aspx
+    state=$($HIVEXGET "$target/windows/system32/config/software" \
+            '\Microsoft\Windows\CurrentVersion\Setup\State')
+
+    case "$(grep '^"ImageState"=' <<< "$state" | cut -d= -f2)" in
+    \"IMAGE_STATE_COMPLETE\")
+        log_error "Image is not sysprepped. Windows customization is only" \
+            "supported for sysprepped images."
+        ;;
+    \"IMAGE_STATE_UNDEPLOYABLE\")
+        log_error "Image is in an undeployable state. Setup seems corrupted."
+        ;;
+    \"IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE\")
+        ;;
+    \"IMAGE_STATE_GENERALIZE_RESEAL_TO_AUDIT\")
+        ;;
+    \"IMAGE_STATE_SPECIALIZE_RESEAL_TO_OOBE\")
+        log_error "Customization is supported only for generalized images." \
+            "You must run sysprep /generalize when creating the image."
+        ;;
+    \"IMAGE_STATE_SPECIALIZE_RESEAL_TO_AUDIT\")
+        log_error "Customization is supported only for generalized images." \
+            "You must run sysprep /generalize when creating the image."
+        ;;
+    *)
+        log_error "Can't check if image is sysprepped. Unknown System State."
+        ;;
+    esac
+}
+
+check_windows-legacy_if_sysprepped() {
+    local target setup
+    target="$1"
+
+    setup=$($HIVEXGET "$target/windows/system32/config/system" '\Setup')
+    if ! grep '"SystemSetupInProgress"=dword:00000001' <<<"$setup" &>/dev/null; then
+        log_error "Image is not sysprepped. Windows customization is only" \
+            "supported for sysprepped images."
+    fi
+
+    if ! grep '"MiniSetupInProgress"=dword:00000001' <<<"$setup" &>/dev/null; then
+        log_error "MiniSetup flag is not set in Sysprep. Windows" \
+            "customization is only supported for sysprepped images with" \
+            "MiniSetup enabled."
     fi
 }
 
