helper: implement the task_init_as function
This function is the first function a configuration task should run.
It hosts common code the tasks should execute and receives as arguments
attributes that characterize the tasks:

* If "excludable" is in the arg list, this task can be prevented from
  running using the EXCLUDE_TASK_<task_name> image property mechanism.
* If "mounted_excludable" is in the arg list, it means that this task
  can be prevented from running using the EXCLUDE_MOUNTED_TASKS image
  property.
* If "fs_resize_excludable" is in the arg list, this task can be
  prevented from running using the EXCLUDE_FILESYSTERESIZE_TASKS image
  property.
* if "overwritable" is in the arg list, the task can be overwritten by
  the image itself.

diff --git a/snf-image-helper/common.sh.in b/snf-image-helper/common.sh.in
--- a/snf-image-helper/common.sh.in
+++ b/snf-image-helper/common.sh.in
@@ -155,6 +155,35 @@ prepare_helper() {
     export HYPERVISOR
 }
 
+task_init_as() {
+    declare -A attr
+    export TASKNAME="$PROGNAME"
+
+    trap task_cleanup EXIT
+    report_task_start
+
+    while (( "$#" )); do
+        attr["$1"]=yes
+        shift
+    done
+
+    if [ -n "${attr[excludable]}" ]; then
+        check_if_excluded
+    fi
+
+    if [ -n "${attr[fs_resize_excludable]}" ]; then
+        check_if_filesystem_resize_excluded
+    fi
+
+    if [ -n "${attr[mounted_excludable]}" ]; then
+        check_if_mounted_excluded
+    fi
+
+    if [ -n "${attr[overwritable]}" ]; then
+        check_if_overwritten
+    fi
+}
+
 report_error() {
     msg=""
     if [ ${#ERRORS[*]} -eq 0 ]; then
@@ -1219,9 +1248,14 @@ check_if_filesystem_resize_excluded() {
 check_if_overwritten() {
     local script ret
 
+    if [ ! -d "$SNF_IMAGE_TARGET" ]; then
+        log_error "Target dir: \`$SNF_IMAGE_TARGET' is missing."
+    fi
+
     if ! check_yes_no SNF_IMAGE_PROPERTY_ALLOW_MOUNTED_TASK_OVERWRITING; then
         return 0
     fi
+
     script=$(find -L $SNF_IMAGE_TARGET/root/snf-image/helper \
              -iname "overwrite_task_${PROGNAME:2}" -type f 2>/dev/null) || true
     if [ -x "$script" ]; then
