Add new inst_properties OS parameter
This can be used to overwrite keys defined in the img_properties OS
parameter. There are cases were the image properties do not reflect
the instance's state and need to be update. For example, a user may
provide cloud-init use-data that create or remove users. snf-image
cannot determine that the list of users, whose password needs to be
set, has changed, unless the user updates the USERS list.

diff --git a/snf-image-helper/snf-image-helper.in b/snf-image-helper/snf-image-helper.in
--- a/snf-image-helper/snf-image-helper.in
+++ b/snf-image-helper/snf-image-helper.in
@@ -106,6 +106,19 @@ if [ -n "$SNF_IMAGE_PROPERTIES" ]; then
     source "$properties"
 fi
 
+# If defined, this may overwrite a number of image properties
+if [ -n "$SNF_IMAGE_INST_PROPERTIES" ]; then
+    properties=$(mktemp --tmpdir properties.XXXXXX)
+    add_cleanup rm "$properties"
+    if ! echo "$SNF_IMAGE_INST_PROPERTIES" | \
+        "@scriptsdir@/decode-properties.py" "$properties"; then
+
+        log_error "Unable to decode instance properties. " \
+             "Please check if the variable is in valid json format."
+    fi
+    source "$properties"
+fi
+
 # Image mount point...
 target=$(mktemp -d --tmpdir target.XXXXXX)
 add_cleanup rmdir "$target"
