Add priority and disable mechanism to back-ends
For every back-end the file <name>.priority and <name>.disabled can be
defined in the back-end configuration directory.

The priority file should contain a 2-digits number that defines a
priority. Modules with higher priority will be examined first when
trying to determine which back-end is suitable to handle a URL. If a
priority file is not present or has an invalid content, the modules
priority will be 50.

If the disable file is present, snf-image will not examine this module
at all.

diff --git a/snf-image-host/common.sh.in b/snf-image-host/common.sh.in
--- a/snf-image-host/common.sh.in
+++ b/snf-image-host/common.sh.in
@@ -370,9 +370,43 @@ create_floppy() {
 get_backend() {
     local target=$1
     local id=$2
-    local bckend answer
+    local bckend answer priority IFS conf
 
     for bckend in "$BACKENDSDIR/${target}"/*; do
+        conf="${CONFDIR}/backends/${target}/$(basename "$bckend")"
+        # Check if the back-end is disabled
+        if [ -f "${conf}.disabled" ]; then
+            log_warning "Not examining disabled back-end: $bckend"
+            continue
+        fi
+
+        # Check if there is a priority file
+        if [ -f "${conf}.priority" ]; then
+            priority=$(cat "${conf}.priority")
+            if ! [[ "$priority" =~ ^[0-9]{1,2}$ ]]; then
+                log_warning "Invalid priority: $priority for $bckend. Using 50."
+                priority=50
+            fi
+        else
+            priority=50
+        fi
+
+        if [ ${#priority} -eq 1 ]; then
+            priority="0$priority"
+        fi
+
+        backends+=("${priority}@${bckend}")
+    done
+
+    # Sort the list of back-ends. Let's hope none has a new line in the
+    # filename. I couldn't make it for with \0 for IFS.
+    IFS=$'\n'
+    mapfile -t backends < <(sort -rn <<< "${backends[*]}")
+    unset IFS
+
+    for bckend in "${backends[@]}"; do
+        # Remove the priority prefix
+        bckend="${bckend:3}"
         if [ -d "$bckend" ]; then
             bckend="${bckend}/$(basename "$bckend")"
         fi
