Add new DEFAULT_NIC_CONFIG configuration parameter
This can be used to define an action for the default NIC that
Ganeti will attach to an instance if none of the --net and --no-nics
input arguments are defined on the instance creation command.

This resolves #90

diff --git a/snf-image-host/common.sh.in b/snf-image-host/common.sh.in
--- a/snf-image-host/common.sh.in
+++ b/snf-image-host/common.sh.in
@@ -562,6 +562,21 @@ fi
 : ${DHCP_TAGS:="auto dhcp nfdhcpd"}
 : ${STATEFUL_DHCPV6_TAGS:="dhcpv6 stateful_dhcpv6"}
 : ${STATELESS_DHCPV6_TAGS:="nfdhcpd stateless_dhcpv6"}
+: ${DEFAULT_NIC_CONFIG:="dhcp"}
+
+found=no
+for val in "" dhcp {dhcp+,}{dhcpv6,slaac,slaac_dhcp}; do
+    if [ "$DEFAULT_NIC_CONFIG" = "$val" ]; then
+        found=yes
+        break
+    fi
+done
+
+if [ "$found" = "no" ]; then
+    log_error "DEFAULT_NIC_CONFIG (=\`$DEFAULT_NIC_CONFIG') has invalid value."
+    log_error "Valid values are: \`'" dhcp {dhcp+,}{dhcpv6,slaac,slaac_dhcp}
+    exit 1
+fi
 
 SCRIPT_NAME=$(basename $0)
 
