Shrink the helper image to the minimum size
Since the helper image is read-only there is no need to waste space.

diff --git a/snf-image-host/snf-image-create-helper.in b/snf-image-host/snf-image-create-helper.in
--- a/snf-image-host/snf-image-create-helper.in
+++ b/snf-image-host/snf-image-create-helper.in
@@ -111,7 +111,7 @@ rm -f "$HELPER_DIR/initrd" "$HELPER_DIR/kernel" "$HELPER_DIR/image"
 echo -n "Allocating space for helper disk image..."
 helper_img=$(mktemp "$HELPER_DIR/image.XXXXXX")
 add_cleanup rm -f "$helper_img"
-dd if=/dev/zero of="$helper_img" bs=1M count="$HELPER_SIZE" &> /dev/null
+truncate -s 2G "$helper_img"
 echo "done"
 
 echo Creating and configuring filesystem...
@@ -125,7 +125,7 @@ target=$(mktemp -d)
 add_cleanup rmdir "$target"
 
 mount "$helper_img" "$target"
-add_cleanup umount "$target"
+add_cleanup ignore_failure umount "$target"
 
 do_multistrap "$target"
 
@@ -182,8 +182,8 @@ if [ -r "$HELPER_PKG" ]; then
     echo "Installing snf-image-helper pkg in the new image..."
     cp "$HELPER_PKG" "$target/tmp/"
     pkg_name=$(basename "$HELPER_PKG")
-    add_cleanup rm "$target/tmp/$pkg_name"
     chroot "$target" dpkg -i "/tmp/$pkg_name" 2>&1 | sed -e 's/^/DPKG: /g'
+    rm "$target/tmp/$pkg_name"
 
     # Recreate package list
     chroot "$target" dpkg-query -W  > "$HELPER_DIR/packages"
@@ -201,6 +201,31 @@ if [ "$VERSION_CHECK" == yes -a -z "$HELPER_PKG" ]; then
         exit 1
     fi
 fi
+
+umount "$target"
+
+echo "Shrinking the created image:" >&2
+set +e
+e2fsck -y -f "$helper_img" 2>&1 | sed -u -e 's/^/E2FSCK: /g'
+ret=$?
+set -e
+
+if [ $ret -ge 4 ]; then
+    log_error "File system check failed!"
+fi
+
+resize2fs -M "$helper_img" 2>&1 2>&1 | sed -u -e 's/^/RESIZE2FS: /g'
+
+while read line; do
+    value="$(echo $(cut -d: -f2 <<< "$line"))"
+    if grep '^Block size:' <<< "$line" &> /dev/null; then
+        block_size="$value"
+    elif grep '^Block count:' <<< "$line" &> /dev/null; then
+        block_count="$value"
+    fi
+done <<< "$(tune2fs -l "$helper_img")"
+
+truncate -s $((block_size*block_count)) "$helper_img"
 
 mv "$helper_img" "$HELPER_DIR/image"
 
