update-helper: add option for omitting checksum
Add an option in snf-image-update-helper for omitting the checksum check
of the helper image.

This resolves #64

diff --git a/snf-image-host/snf-image-update-helper.in b/snf-image-host/snf-image-update-helper.in
--- a/snf-image-host/snf-image-update-helper.in
+++ b/snf-image-host/snf-image-update-helper.in
@@ -41,14 +41,16 @@ This script will download a suitable fixed snf-image-helper image and will
 install it under $HELPER_DIR.
 
 OPTIONS:
+    -c Don't check the checksum of the helper image
+
+    -f Force the installation even if the snf-image and helper versions don't match
+
     -h Print this message
 
     -u URL
        Download URL to use for the helper image instead of $HELPER_URL
 
     -y Assume Yes to all queries and do not prompt
-
-    -f Force the installation even if the snf-image and helper versions don't match
 
 EOF
 
@@ -57,13 +59,15 @@ EOF
 
 while getopts "hu:yf" opt; do
     case $opt in
+        c) NO_CHECKSUM="yes"
+            ;;
+        f) FORCE="yes"
+            ;;
         h) usage 0
             ;;
         u) HELPER_URL="$OPTARG"
             ;;
         y) NO_PROMPT="yes"
-            ;;
-        f) FORCE="yes"
             ;;
         ?) log_error "User \`-h' for help"; exit 1
             ;;
@@ -119,19 +123,22 @@ if [ $RET -ne 0 -a $RET -ne 141 ]; then
     exit 1
 fi
 
-add_cleanup rm -f "$IMAGE_DIR/$IMAGE.md5sum"
-set +e
-$CURL -O -L -f "$HELPER_URL.md5sum"
-RET=$?
-set -e
+if [ "x$NO_CHECKSUM" != "xyes" ]; then
+    echo "Checking the helper image checksum ..." >&2
+    add_cleanup rm -f "$IMAGE_DIR/$IMAGE.md5sum"
+    set +e
+    $CURL -O -L -f "$HELPER_URL.md5sum"
+    RET=$?
+    set -e
 
-# See above for an explaination
-if [ $RET -ne 0 -a $RET -ne 141 ]; then
-    log_error "Downloading "$IMAGE.md5sum" from "$HELPER_URL.md5sum" failed"
-    exit 1
+    # See above for an explanation
+    if [ $RET -ne 0 -a $RET -ne 141 ]; then
+        log_error "Downloading "$IMAGE.md5sum" from "$HELPER_URL.md5sum" failed"
+        exit 1
+    fi
+
+    $MD5SUM -c "$IMAGE_DIR/$IMAGE.md5sum"
 fi
-
-$MD5SUM -c "$IMAGE_DIR/$IMAGE.md5sum"
 
 cd "$HELPER_DIR"
 
