Create a package list file after every debootstrap
This file is used to check if the cache file contains every package
defined in HELPER_EXTRA_PKGS.

diff --git a/snf-image-host/snf-image-update-helper.in b/snf-image-host/snf-image-update-helper.in
--- a/snf-image-host/snf-image-update-helper.in
+++ b/snf-image-host/snf-image-update-helper.in
@@ -149,10 +149,37 @@ mount "$root_dev" "$target"
 add_cleanup umount "$root_dev"
 
 echo -n "Checking for cached root filesystem file \`$CACHE_FILE'..."
-if [  -f "$CACHE_FILE" ]; then
+if [ -f "$CACHE_FILE" ]; then
     echo "found"
 
-    while [[ 1 ]]; do
+
+    missing_pkgs="no"
+    if [ "$CACHE_FILE" == "$HELPER_CACHE_FILE" ]; then
+        echo -n "Checking if needed packages are present..."
+        if [ ! -f "$HELPER_CACHE_PKGS" ]; then
+            missing_pkgs="yes"
+            echo "packages file: \`$HELPER_CACHE_PKGS' does not exist"
+        else
+            OLD_IFS="$IFS"
+            IFS=,; for pkg in $HELPER_EXTRA_PKGS; do
+                if ! grep "^$pkg\$" "$HELPER_CACHE_PKGS" > /dev/null; then
+		    missing_pkgs="yes"
+                    echo "$pkg is missing."
+                    break
+                fi
+            done
+            IFS="$OLD_IFS"
+            if [ "$missing_pkgs" == "no" ]; then
+                echo "done"
+            fi
+	fi
+        if [ "$missing_pkgs" == "yes" ]; then
+                do_debootstrap "$target"
+        fi
+    fi
+
+
+    test "$missing_pkgs" == "no" && while [[ 1 ]]; do
         echo -n "Use the cached file [Y/n]? "
         if [ "x$NO_PROMPT" = "xyes" ]; then
             echo "y";
@@ -168,6 +195,7 @@ if [  -f "$CACHE_FILE" ]; then
             break;
         fi
     done
+
 else
     echo "not found"
     do_debootstrap "$target"
