Add new os_product_key parameter
This can be used to license a Windows deployment

diff --git a/snf-image-host/verify b/snf-image-host/verify
--- a/snf-image-host/verify
+++ b/snf-image-host/verify
@@ -24,7 +24,7 @@ set -e
 
 check_required() {
     local required_params="IMG_ID IMG_FORMAT"
-    local osparams="$required_params IMG_PASSWD IMG_PROPERTIES IMG_PERSONALITY CONFIG_URL"
+    local osparams="$required_params IMG_PASSWD IMG_PROPERTIES IMG_PERSONALITY CONFIG_URL OS_PRODUCT_KEY"
     local osp
 
     source_variant
@@ -41,10 +41,18 @@ check_required() {
 
     for var in $required_params; do
         if [ -z "${!var}" ]; then
-             log_error "Missing OS API Parameter: ${var}"
+             log_error "Missing OS API Parameter: ${var,,}"
              exit 1
         fi
     done
+
+    if [ -n "${OS_PRODUCT_KEY+dummy}" ]; then
+        if [[ ! "${OS_PRODUCT_KEY}" =~ ^([a-zA-Z0-9]{5}-){3}[a-zA-Z0-9]{5}$ ]]; then
+            log_error "Invalid OS API Parameter: os_product_key."
+            log_error "Valid format is: XXXXX-XXXXX-XXXXX-XXXXX"
+            exit 1
+        fi
+    fi
 }
 
 if [ -z "$OSP_CONFIG_URL" ]; then
