Make mounting NTFS more robust
Use lowntfs-3g with appropriate options when mounting NTFS-based Images:
    * ensure path lookup is case-insensitive,
    * prevent the creation of files with names which are not allowed
      under Windows,
    * complain loudly if the filesystem is dirty or needs recovery.

Mounting the filesystem in a case-insensitive way can simplify task code
significantly; there is no reason to perform case-insensitive lookups
explicitly ("Unattend.xml" vs. "unattend.xml"). It also ensures
attempting to inject "filea" in the image will overwrite "fileA", if it
already exists, as it would under Windows, instead of leading to a
situation where both "fileA" and "filea" exist, causing all sorts of
problems later on.

Finally, complain loudly when attempting to mount an NTFS marked dirty
(requiring a disk check on next boot), or with an unclean journal.
NTFS-3G code seems to wipe the NTFS journal instead of replaying it, and
may lead to data corruption. Images should not contain dirty
filesystems.

See
http://tuxera.com/forum/viewtopic.php?f=2&t=30562:
"Actually the journal is simply wiped out. This is to prevent the
journal to be applied at next mounting on Windows to data which may have
been changed in the meantime.", and
"So far, nobody has been able to understand how the journal is
organized, so there is no real recovery in ntfs-3g, just wiping the
journal."

Also:
http://www.tuxera.com/community/ntfs-3g-manual/
"recover: Recover and try to mount a partition which was not unmounted
properly by Windows. The Windows logfile is cleared, which may cause
inconsistencies. Currently this is the default option."

In the future, it would be best to reject the Image outright,
instead of continuing.

diff --git a/snf-image-helper/tasks/30MountImage.in b/snf-image-helper/tasks/30MountImage.in
--- a/snf-image-helper/tasks/30MountImage.in
+++ b/snf-image-helper/tasks/30MountImage.in
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-# Copyright (C) 2011 GRNET S.A. 
+# Copyright (C) 2011, 2015 GRNET S.A. and individual contributors
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -60,6 +60,31 @@ if [[ "$SNF_IMAGE_PROPERTY_OSFAMILY" == *bsd ]]; then
 
     # See mount_all() for a reason why we do this
     $MOUNT -o remount,rw "$SNF_IMAGE_TARGET"
+elif [ "$SNF_IMAGE_PROPERTY_OSFAMILY" = "windows" ]; then
+    # Special case for Windows:
+    # Perform a case-insensitive, all-lowercase mount with 'lowntfs-3g'
+    # to avoid problems with different case between installations,
+    # e.g., C:\WINDOWS vs. C:\Windows, and simplify path lookups.
+    #
+    NTFS_OPTS="ignore_case,windows_names,rw"
+
+    # Be extra safe: Warn when attempting to work on a dirty NTFS.
+    # In the future, it would be best to reject the Image outright.
+    if ! $NTFSINFO -m "$rootdev"; then
+        warn "Failed to get NTFS info, fs may be dirty (scheduled for CHKDSK)."
+        warn "Please fix your Image. Future versions will refuse to continue."
+    fi
+
+    if ! $MOUNT -t lowntfs-3g -o "$NTFS_OPTS,norecover" "$rootdev" \
+        "$SNF_IMAGE_TARGET"; then
+        warn "Failed to mount NTFS, fs may be unclean and need recovery."
+        warn "Please fix your Image. Future versions will refuse to continue."
+        # It would be best to fail here. NTFS-3G based recovery
+        # is based on wiping off the NTFS journal instead of replaying it,
+        # and may lead to data corruption.
+        warn "Attempting to mount NTFS again (allowing unclean filesystem)"
+        $MOUNT -t lowntfs-3g -o "$NTFS_OPTS" "$rootdev" "$SNF_IMAGE_TARGET"
+    fi
 else
     $MOUNT -o rw "$rootdev" "$SNF_IMAGE_TARGET"
 fi
