Add support for Windows XP / Server 2003 Images
Introduce support for Windows XP / Server 2003 Images.

To do this:
    * Extend common.sh and 40InstallUnattend so they can also detect
      Windows XP / Server 2003 SYSPREP.INF answer files.
    * Extend 50AssignHostname so it can set the hostname inside
      SYSPREP.INF, based on a small handle-ini-file.py utility.
    * Remove the seemingly unnecessary addition of /LOGONPASSWORDCHG:NO,
      which is unsupported under XP / Server 2003. More on this below.
    * Warn the user about Windows XP / Server 2003 not supporting
      online NTFS resize, and the need to use OFFLINE_NTFSRESIZE
      instead.

Regarding the use of /LOGONPASSWORDCHG:NO while using NET USER
to change a user password:
    * This argument is unsupported under Windows XP / Server 2003,
      see http://blog.johnmuellerbooks.com/2011/04/12/working-with-net-user/
    * Its default value is "NO" anyway, so it shouldn't make a
      difference whether it is explicitly specified in the command line
      or not:
      https://answers.microsoft.com/en-us/windows/forum/windows_vista-security/setting-up-passwords-for-new-users/1704349b-31a3-4340-ae9e-1473c5adb919
    * Even if the security policies of a specific Image were set up
      in such way that users *were* required to change their passwords
      immediately upon their first logon, it is not snf-image's job
      to modify this behavior by specifying /LOGONPASSWORDCHG:NO.
      The password policy is Image-specific, and snf-image shouldn't
      mess with it.

diff --git a/snf-image-helper/tasks/40InstallUnattend.in b/snf-image-helper/tasks/40InstallUnattend.in
--- a/snf-image-helper/tasks/40InstallUnattend.in
+++ b/snf-image-helper/tasks/40InstallUnattend.in
@@ -1,6 +1,6 @@
 #! /bin/bash
 
-# Copyright (C) 2011 GRNET S.A. 
+# Copyright (C) 2011, 2015 GRNET S.A. and individual contributors
 #
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -63,6 +63,10 @@ else
     fi
 fi
 
+# FIXME: There is no guarantee the answer file is actually named
+# C:\unattend.xml. These may have to be modified to use the actual
+# name of the answer file, as returned by get_unattend().
+
 echo "del /Q /F C:\unattend.xml" > \
         "$target/Windows/Setup/Scripts/SetupComplete.cmd"
 
@@ -85,6 +89,44 @@ echo "del /Q /F C:\Windows\SnfScripts\ChangeAdminPassword.cmd" >> \
 
 echo "rmdir C:\Windows\SnfScripts" >> \
         "$target/Windows/Setup/Scripts/SetupComplete.cmd"
+
+# If using an old-style (XP / Server 2003) SYSPREP.INF answer file,
+# ensure C:\SnfScripts\SetupComplete.cmd is executed via CmdLines.txt
+# which must be installed in the InstalledfilesPath from SYSPREP.INF.
+sysprepinf=$(get_sysprepinf "$target")
+if [ -n "$sysprepinf" ]; then
+    h=@scriptsdir@/handle-ini-file.py
+    installfilespath=$($h "$sysprepinf" get Unattended InstallFilesPath)
+    if [ -z "$installfilespath" ]; then
+        # Set InstallFilesPath to C:\SYSPREP\i386 explicitly, if missing
+        $h "$sysprepinf" set Unattended InstallFilesPath 'C:\SYSPREP\i386'
+        installfilespath=$($h "$sysprepinf" get Unattended InstallFilesPath)
+    fi
+    if [ -z "$installfilespath" ]; then
+        log_error "Failed to get value of InstallFilesPath in SYSPREP.INF"
+    fi
+    installfilespath=$(tr [A-Z] [a-z] <<< "$installfilespath")
+
+    if [[ ! "$installfilespath" == 'c:\sysprep\'* ]]; then
+        log_error "InstallFilesPath from SYSPREP.INF not under C:\\SYSPREP\\"
+    fi
+    installfilespath=${installfilespath#'c:\sysprep\'}
+    installfilespath=$(echo "$installfilespath"|sed 's/\\/\//g')
+
+    # Ensure final location for InstallFilesPath is still under $target
+    oemdir="$target"/sysprep/"$installfilespath"/'$OEM$'
+    if ! readlink -f "$oemdir"|grep -q "^$target"; then
+        log_error "Invalid value for InstallFilesPath in SYSPREP.INF"
+    fi
+
+    mkdir -p "$oemdir"
+    cmdlinestxt="$oemdir"/CmdLines.txt
+    if [ ! -f "$cmdlinestxt" ]; then
+        echo "[Commands]" >"$cmdlinestxt"
+    fi
+    echo "\"C:\\Windows\\SnfScripts\\ChangeAdminPassword.cmd\"" >>"$cmdlinestxt"
+    echo "\"C:\\Windows\\Setup\\Scripts\\SetupComplete.cmd\"" >>"$cmdlinestxt"
+fi
 
 exit 0
 
